List<String> getQuotes() {
  return [
    "Choose a job you love, and you will never have to work a day in your life.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "Do what you can, with what you have, where you are.",
    "The only way to do great work is to love what you do.",
    "Opportunities don't happen. You create them.",
    "Success usually comes to those who are too busy to be looking for it.",
    "Don't watch the clock; do what it does. Keep going.",
    "The future depends on what you do today.",
    "Dream big. Start small. Act now.",
    "Success is not in what you have, but who you are.",
    "Strive not to be a success, but rather to be of value.",
    "Your time is limited, so don’t waste it living someone else’s life.",
    "I’m not a product of my circumstances. I am a product of my decisions.",
    "If opportunity doesn’t knock, build a door.",
    "Hard work beats talent when talent doesn’t work hard.",
    "You don’t have to be great to start, but you have to start to be great.",
    "Don’t be pushed around by the fears in your mind.",
    "You miss 100% of the shots you don’t take.",
    "The best way to predict the future is to create it.",
    "Start where you are. Use what you have. Do what you can.",
    "Action is the foundational key to all success.",
    "Do not wait to strike till the iron is hot; but make it hot by striking.",
    "A year from now you may wish you had started today.",
    "The harder you work for something, the greater you’ll feel when you achieve it.",
    "Push yourself, because no one else is going to do it for you.",
    "Work hard in silence, let your success be your noise.",
    "Great things never come from comfort zones.",
    "Don’t limit your challenges. Challenge your limits.",
    "Believe you can and you're halfway there.",
    "Discipline is doing what needs to be done, even if you don’t want to do it.",
    "Motivation gets you going, but discipline keeps you growing.",
    "If you’re going through hell, keep going.",
    "Success isn’t always about greatness. It’s about consistency.",
    "Small progress is still progress.",
    "Your limitation—it’s only your imagination.",
    "Push through the pain. Great things take time.",
    "Doubt kills more dreams than failure ever will.",
    "Never give up on a dream just because of the time it will take to accomplish it.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "Hustle in silence and let your success make the noise.",
    "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    "Don't be busy, be productive.",
    "You don't need to see the whole staircase, just take the first step.",
    "Don't raise your voice, improve your argument.",
    "Make each day your masterpiece.",
    "It's not about ideas. It's about making ideas happen.",
    "There are no shortcuts to any place worth going.",
    "If you don’t build your dream, someone else will hire you to help them build theirs.",
    "The expert in anything was once a beginner.",
    "If you're not willing to risk the usual, you’ll have to settle for the ordinary."
  ];
}